version: '3'
services:
  web:
    image: nginx:latest
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build: .
    volumes:
      - .:/var/www
    env_file: .env
